// <auto-generated />
using System;
using ConsultorioMedAPP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultorioMedAPP.Migrations
{
    [DbContext(typeof(ConsultorioMedDBContext))]
    [Migration("20251107030839_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsultorioMedAPP.Models.AntecedentesMedico", b =>
                {
                    b.Property<int>("IdAntecedentesMedicos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdAntecedentes_Medicos");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAntecedentesMedicos"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("Cronico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdCedula")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoEnfermedad")
                        .HasColumnType("int")
                        .HasColumnName("IdTipo_Enfermedad");

                    b.HasKey("IdAntecedentesMedicos")
                        .HasName("PK__Antecede__D3CC663466CDEFF2");

                    b.HasIndex("IdCedula");

                    b.HasIndex("IdTipoEnfermedad");

                    b.ToTable("Antecedentes_Medicos", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Auditorium", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("DireccionIP");

                    b.Property<DateTime?>("FechaAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("int")
                        .HasColumnName("RegistroID");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("Usuario_IdUsuario");

                    b.Property<string>("ValorAnterior")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ValorNuevo")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("IdAuditoria")
                        .HasName("PK__Auditori__7FD13FA061CC21DB");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Citum", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<int>("DoctorIdCedula")
                        .HasColumnType("int")
                        .HasColumnName("Doctor_idCedula");

                    b.Property<int>("EstadoCitaIdEstadoCita")
                        .HasColumnType("int")
                        .HasColumnName("EstadoCita_idEstadoCita");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("PacienteIdCedula")
                        .HasColumnType("int")
                        .HasColumnName("Paciente_idCedula");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("IdCita")
                        .HasName("PK__Cita__394B020205DDB0BF");

                    b.HasIndex("DoctorIdCedula");

                    b.HasIndex("EstadoCitaIdEstadoCita");

                    b.HasIndex("PacienteIdCedula");

                    b.ToTable("Cita");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Correo", b =>
                {
                    b.Property<int>("IdCorreo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCorreo"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("DirecCorreo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Direc_Correo");

                    b.Property<int>("IdCedula")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoCorreo")
                        .HasColumnType("int")
                        .HasColumnName("IdTipo_Correo");

                    b.HasKey("IdCorreo")
                        .HasName("PK__Correo__872F8EAE8E89A8E2");

                    b.HasIndex("IdCedula");

                    b.HasIndex("IdTipoCorreo");

                    b.ToTable("Correo", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.DetalleFactura", b =>
                {
                    b.Property<int>("IdDetalleFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleFactura"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("FacturaIdFactura")
                        .HasColumnType("int")
                        .HasColumnName("Factura_IdFactura");

                    b.Property<int>("IdCitaCita")
                        .HasColumnType("int")
                        .HasColumnName("IdCita_Cita");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(13, 2)");

                    b.HasKey("IdDetalleFactura")
                        .HasName("PK__Detalle___DB5F463128D4DCBA");

                    b.HasIndex("FacturaIdFactura");

                    b.HasIndex("IdCitaCita");

                    b.ToTable("Detalle_Factura", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Diagnostico", b =>
                {
                    b.Property<int>("IdDiagnostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiagnostico"));

                    b.Property<int>("CitaIdCita")
                        .HasColumnType("int")
                        .HasColumnName("Cita_IdCita");

                    b.Property<string>("CodigoDiagnostico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("FechaDiagnostico")
                        .HasColumnType("date");

                    b.Property<string>("Recomendaciones")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("IdDiagnostico")
                        .HasName("PK__Diagnost__BD16DB697B9DBF64");

                    b.HasIndex("CitaIdCita");

                    b.ToTable("Diagnostico", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Doctor", b =>
                {
                    b.Property<int>("IdCedula")
                        .HasColumnType("int");

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("int");

                    b.HasKey("IdCedula")
                        .HasName("PK__Doctor__7485273046802B18");

                    b.HasIndex("IdEspecialidad");

                    b.ToTable("Doctor", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Especialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdEspecialidad")
                        .HasName("PK__Especial__693FA0AF91024FBF");

                    b.ToTable("Especialidad", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.EstadoCitum", b =>
                {
                    b.Property<int>("IdEstadoCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoCita"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.HasKey("IdEstadoCita")
                        .HasName("PK__EstadoCi__EF486D223204E7DE");

                    b.ToTable("EstadoCita");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<DateOnly>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("Impuesto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(13, 2)");

                    b.HasKey("IdFactura")
                        .HasName("PK__Factura__50E7BAF1BD327356");

                    b.HasIndex(new[] { "NumeroFactura" }, "UQ__Factura__CF12F9A6451A4456")
                        .IsUnique();

                    b.ToTable("Factura", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGenero"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdGenero")
                        .HasName("PK__Genero__0F834988AFA00C99");

                    b.ToTable("Genero", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInventario"));

                    b.Property<string>("DetalleInventario")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProductoIdProducto")
                        .HasColumnType("int")
                        .HasColumnName("Producto_IdProducto");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("IdInventario")
                        .HasName("PK__Inventar__1927B20C8ED0BF0A");

                    b.HasIndex("ProductoIdProducto");

                    b.ToTable("Inventario", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Medicina", b =>
                {
                    b.Property<int>("IdMedicinas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedicinas"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdDiagnostico")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdMedicinas")
                        .HasName("PK__Medicina__2230931489006481");

                    b.HasIndex("IdDiagnostico");

                    b.HasIndex("IdProducto");

                    b.ToTable("Medicinas");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Paciente", b =>
                {
                    b.Property<int>("IdCedula")
                        .HasColumnType("int");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SeguroPacienteIdSeguro")
                        .HasColumnType("int")
                        .HasColumnName("SeguroPaciente_idSeguro");

                    b.HasKey("IdCedula")
                        .HasName("PK__Paciente__7485273009008672");

                    b.HasIndex("SeguroPacienteIdSeguro");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Persona", b =>
                {
                    b.Property<int>("IdCedula")
                        .HasColumnType("int");

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Nacimiento");

                    b.Property<int>("IdGenero")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdCedula")
                        .HasName("PK__Persona__748527307F727542");

                    b.HasIndex("IdGenero");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int?>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.HasKey("IdProducto")
                        .HasName("PK__Producto__09889210AFBCEE65");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.HasKey("IdProveedor")
                        .HasName("PK__Proveedo__E8B631AF764EAE80");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Reorden", b =>
                {
                    b.Property<int>("IdReorden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReorden"));

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProductoIdProducto")
                        .HasColumnType("int")
                        .HasColumnName("Producto_IdProducto");

                    b.HasKey("IdReorden")
                        .HasName("PK__Reorden__5C9CA002B2878CF4");

                    b.HasIndex("ProductoIdProducto");

                    b.ToTable("Reorden", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.RolUsuario", b =>
                {
                    b.Property<int>("IdRolUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRolUsuario"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdRolUsuario")
                        .HasName("PK__RolUsuar__3FC7F91FBA54CD2B");

                    b.ToTable("RolUsuario", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Seguro", b =>
                {
                    b.Property<int>("IdSeguro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeguro"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCedula")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoSeguro")
                        .HasColumnType("int")
                        .HasColumnName("IdTipo_Seguro");

                    b.HasKey("IdSeguro")
                        .HasName("PK__Seguro__730AB2BA36336805");

                    b.HasIndex("IdCedula");

                    b.HasIndex("IdTipoSeguro");

                    b.ToTable("Seguro", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Telefono", b =>
                {
                    b.Property<int>("IdTelefono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTelefono"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdCedula")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoTelefono")
                        .HasColumnType("int")
                        .HasColumnName("IdTipo_Telefono");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.HasKey("IdTelefono")
                        .HasName("PK__Telefono__9B8AC753509AFCE2");

                    b.HasIndex("IdCedula");

                    b.HasIndex("IdTipoTelefono");

                    b.ToTable("Telefono", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.TipoCorreo", b =>
                {
                    b.Property<int>("IdTipoCorreo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTipo_Correo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoCorreo"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTipoCorreo")
                        .HasName("PK__Tipo_Cor__7F323C75CE951642");

                    b.ToTable("Tipo_Correo", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.TipoEnfermedad", b =>
                {
                    b.Property<int>("IdTipoEnfermedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTipo_Enfermedad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoEnfermedad"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTipoEnfermedad")
                        .HasName("PK__Tipo_Enf__4C402D9E6618A37C");

                    b.ToTable("Tipo_Enfermedad", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.TipoSeguro", b =>
                {
                    b.Property<int>("IdTipoSeguro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTipo_Seguro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoSeguro"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Porcentaje")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("IdTipoSeguro")
                        .HasName("PK__Tipo_Seg__6834CDAC05C6B3B1");

                    b.ToTable("Tipo_Seguro", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.TipoTelefono", b =>
                {
                    b.Property<int>("IdTipoTelefono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTipo_Telefono");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoTelefono"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTipoTelefono")
                        .HasName("PK__Tipo_Tel__B2049411D6EAF689");

                    b.ToTable("Tipo_Telefono", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.TipoTurno", b =>
                {
                    b.Property<int>("IdTipoTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTipo_Turno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoTurno"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeOnly>("HoraEntrada")
                        .HasColumnType("time")
                        .HasColumnName("Hora_Entrada");

                    b.Property<TimeOnly>("HoraSalida")
                        .HasColumnType("time")
                        .HasColumnName("Hora_Salida");

                    b.HasKey("IdTipoTurno")
                        .HasName("PK__Tipo_Tur__40BD99EB12BACB20");

                    b.ToTable("Tipo_Turno", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurno"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdCedula")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoTurno")
                        .HasColumnType("int")
                        .HasColumnName("IdTipo_Turno");

                    b.HasKey("IdTurno")
                        .HasName("PK__Turno__C1ECF79A59E07C58");

                    b.HasIndex("IdCedula");

                    b.HasIndex("IdTipoTurno");

                    b.ToTable("Turno", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PersonasIdCedula")
                        .HasColumnType("int")
                        .HasColumnName("Personas_IdCedula");

                    b.Property<int>("RolUsuarioIdRolUsuario")
                        .HasColumnType("int")
                        .HasColumnName("RolUsuario_IdRolUsuario");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF97590CF5DB");

                    b.HasIndex("RolUsuarioIdRolUsuario");

                    b.HasIndex(new[] { "PersonasIdCedula" }, "UQ__Usuario__89A413B99E6383F6")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.AntecedentesMedico", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Paciente", "IdCedulaNavigation")
                        .WithMany("AntecedentesMedicos")
                        .HasForeignKey("IdCedula")
                        .IsRequired()
                        .HasConstraintName("FK_Antecedente_Paciente");

                    b.HasOne("ConsultorioMedAPP.Models.TipoEnfermedad", "IdTipoEnfermedadNavigation")
                        .WithMany("AntecedentesMedicos")
                        .HasForeignKey("IdTipoEnfermedad")
                        .IsRequired()
                        .HasConstraintName("FK_Antecedente_Tipo");

                    b.Navigation("IdCedulaNavigation");

                    b.Navigation("IdTipoEnfermedadNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Auditorium", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Usuario", "UsuarioIdUsuarioNavigation")
                        .WithMany("Auditoria")
                        .HasForeignKey("UsuarioIdUsuario")
                        .HasConstraintName("FK_Auditoria_Usuario");

                    b.Navigation("UsuarioIdUsuarioNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Citum", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Doctor", "DoctorIdCedulaNavigation")
                        .WithMany("Cita")
                        .HasForeignKey("DoctorIdCedula")
                        .IsRequired()
                        .HasConstraintName("FK_Cita_Doctor");

                    b.HasOne("ConsultorioMedAPP.Models.EstadoCitum", "EstadoCitaIdEstadoCitaNavigation")
                        .WithMany("Cita")
                        .HasForeignKey("EstadoCitaIdEstadoCita")
                        .IsRequired()
                        .HasConstraintName("FK_Cita_Estado");

                    b.HasOne("ConsultorioMedAPP.Models.Paciente", "PacienteIdCedulaNavigation")
                        .WithMany("Cita")
                        .HasForeignKey("PacienteIdCedula")
                        .IsRequired()
                        .HasConstraintName("FK_Cita_Paciente");

                    b.Navigation("DoctorIdCedulaNavigation");

                    b.Navigation("EstadoCitaIdEstadoCitaNavigation");

                    b.Navigation("PacienteIdCedulaNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Correo", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Persona", "IdCedulaNavigation")
                        .WithMany("Correos")
                        .HasForeignKey("IdCedula")
                        .IsRequired()
                        .HasConstraintName("FK_Correo_Persona");

                    b.HasOne("ConsultorioMedAPP.Models.TipoCorreo", "IdTipoCorreoNavigation")
                        .WithMany("Correos")
                        .HasForeignKey("IdTipoCorreo")
                        .IsRequired()
                        .HasConstraintName("FK_Correo_Tipo");

                    b.Navigation("IdCedulaNavigation");

                    b.Navigation("IdTipoCorreoNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.DetalleFactura", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Factura", "FacturaIdFacturaNavigation")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("FacturaIdFactura")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleFactura_Factura");

                    b.HasOne("ConsultorioMedAPP.Models.Citum", "IdCitaCitaNavigation")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("IdCitaCita")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleFactura_Cita");

                    b.Navigation("FacturaIdFacturaNavigation");

                    b.Navigation("IdCitaCitaNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Diagnostico", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Citum", "CitaIdCitaNavigation")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("CitaIdCita")
                        .IsRequired()
                        .HasConstraintName("FK_Diagnostico_Cita");

                    b.Navigation("CitaIdCitaNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Doctor", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Persona", "IdCedulaNavigation")
                        .WithOne("Doctor")
                        .HasForeignKey("ConsultorioMedAPP.Models.Doctor", "IdCedula")
                        .IsRequired()
                        .HasConstraintName("FK_Doctor_Persona");

                    b.HasOne("ConsultorioMedAPP.Models.Especialidad", "IdEspecialidadNavigation")
                        .WithMany("Doctors")
                        .HasForeignKey("IdEspecialidad")
                        .IsRequired()
                        .HasConstraintName("FK_Doctor_Especialidad");

                    b.Navigation("IdCedulaNavigation");

                    b.Navigation("IdEspecialidadNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Inventario", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Producto", "ProductoIdProductoNavigation")
                        .WithMany("Inventarios")
                        .HasForeignKey("ProductoIdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Inventario_Producto");

                    b.Navigation("ProductoIdProductoNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Medicina", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Diagnostico", "IdDiagnosticoNavigation")
                        .WithMany("Medicinas")
                        .HasForeignKey("IdDiagnostico")
                        .IsRequired()
                        .HasConstraintName("FK_Medicina_Diagnostico");

                    b.HasOne("ConsultorioMedAPP.Models.Producto", "IdProductoNavigation")
                        .WithMany("Medicinas")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Medicina_Producto");

                    b.Navigation("IdDiagnosticoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Paciente", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Persona", "IdCedulaNavigation")
                        .WithOne("Paciente")
                        .HasForeignKey("ConsultorioMedAPP.Models.Paciente", "IdCedula")
                        .IsRequired()
                        .HasConstraintName("FK_Paciente_Persona");

                    b.HasOne("ConsultorioMedAPP.Models.Seguro", "SeguroPacienteIdSeguroNavigation")
                        .WithMany("Pacientes")
                        .HasForeignKey("SeguroPacienteIdSeguro")
                        .HasConstraintName("FK_Paciente_Seguro");

                    b.Navigation("IdCedulaNavigation");

                    b.Navigation("SeguroPacienteIdSeguroNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Persona", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Genero", "IdGeneroNavigation")
                        .WithMany("Personas")
                        .HasForeignKey("IdGenero")
                        .IsRequired()
                        .HasConstraintName("FK_Persona_Genero");

                    b.Navigation("IdGeneroNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Producto", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Proveedor", "IdProveedorNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdProveedor")
                        .HasConstraintName("FK_Producto_Proveedor");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Reorden", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Producto", "ProductoIdProductoNavigation")
                        .WithMany("Reordens")
                        .HasForeignKey("ProductoIdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Reorden_Producto");

                    b.Navigation("ProductoIdProductoNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Seguro", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Persona", "IdCedulaNavigation")
                        .WithMany("Seguros")
                        .HasForeignKey("IdCedula")
                        .IsRequired()
                        .HasConstraintName("FK_Seguro_Persona");

                    b.HasOne("ConsultorioMedAPP.Models.TipoSeguro", "IdTipoSeguroNavigation")
                        .WithMany("Seguros")
                        .HasForeignKey("IdTipoSeguro")
                        .IsRequired()
                        .HasConstraintName("FK_Seguro_Tipo");

                    b.Navigation("IdCedulaNavigation");

                    b.Navigation("IdTipoSeguroNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Telefono", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Persona", "IdCedulaNavigation")
                        .WithMany("Telefonos")
                        .HasForeignKey("IdCedula")
                        .IsRequired()
                        .HasConstraintName("FK_Telefono_Persona");

                    b.HasOne("ConsultorioMedAPP.Models.TipoTelefono", "IdTipoTelefonoNavigation")
                        .WithMany("Telefonos")
                        .HasForeignKey("IdTipoTelefono")
                        .IsRequired()
                        .HasConstraintName("FK_Telefono_Tipo");

                    b.Navigation("IdCedulaNavigation");

                    b.Navigation("IdTipoTelefonoNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Turno", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Doctor", "IdCedulaNavigation")
                        .WithMany("Turnos")
                        .HasForeignKey("IdCedula")
                        .IsRequired()
                        .HasConstraintName("FK_Turno_Doctor");

                    b.HasOne("ConsultorioMedAPP.Models.TipoTurno", "IdTipoTurnoNavigation")
                        .WithMany("Turnos")
                        .HasForeignKey("IdTipoTurno")
                        .IsRequired()
                        .HasConstraintName("FK_Turno_Tipo");

                    b.Navigation("IdCedulaNavigation");

                    b.Navigation("IdTipoTurnoNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Usuario", b =>
                {
                    b.HasOne("ConsultorioMedAPP.Models.Persona", "PersonasIdCedulaNavigation")
                        .WithOne("Usuario")
                        .HasForeignKey("ConsultorioMedAPP.Models.Usuario", "PersonasIdCedula")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Persona");

                    b.HasOne("ConsultorioMedAPP.Models.RolUsuario", "RolUsuarioIdRolUsuarioNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolUsuarioIdRolUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Rol");

                    b.Navigation("PersonasIdCedulaNavigation");

                    b.Navigation("RolUsuarioIdRolUsuarioNavigation");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Citum", b =>
                {
                    b.Navigation("DetalleFacturas");

                    b.Navigation("Diagnosticos");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Diagnostico", b =>
                {
                    b.Navigation("Medicinas");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Doctor", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Especialidad", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.EstadoCitum", b =>
                {
                    b.Navigation("Cita");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Factura", b =>
                {
                    b.Navigation("DetalleFacturas");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Genero", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Paciente", b =>
                {
                    b.Navigation("AntecedentesMedicos");

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Persona", b =>
                {
                    b.Navigation("Correos");

                    b.Navigation("Doctor");

                    b.Navigation("Paciente");

                    b.Navigation("Seguros");

                    b.Navigation("Telefonos");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Producto", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("Medicinas");

                    b.Navigation("Reordens");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.RolUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Seguro", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.TipoCorreo", b =>
                {
                    b.Navigation("Correos");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.TipoEnfermedad", b =>
                {
                    b.Navigation("AntecedentesMedicos");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.TipoSeguro", b =>
                {
                    b.Navigation("Seguros");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.TipoTelefono", b =>
                {
                    b.Navigation("Telefonos");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.TipoTurno", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ConsultorioMedAPP.Models.Usuario", b =>
                {
                    b.Navigation("Auditoria");
                });
#pragma warning restore 612, 618
        }
    }
}
